#pragma once
#define NUMBER_OF_LOGICAL_CORES 12
#define NUMBER_OF_PHYSICAL_CORES 6
#define TOTAL_VIRTUAL_MEMORY 36552
#define AVAILABLE_VIRTUAL_MEMORY 20498
#define TOTAL_PHYSICAL_MEMORY 16072
#define AVAILABLE_PHYSICAL_MEMORY 5332
#define IS_64BIT 1
#define HAS_FPU 1
#define HAS_MMX 1
#define HAS_MMX_PLUS 0
#define HAS_SSE 1
#define HAS_SSE2 1
#define HAS_SSE_FP 0
#define HAS_SSE_MMX 0
#define HAS_AMD_3DNOW 0
#define HAS_AMD_3DNOW_PLUS 0
#define HAS_IA64 0
#define OS_NAME "Windows"
#define OS_RELEASE " Professional"
#define OS_VERSION " (Build 22631)"
#define OS_PLATFORM "AMD64"
