message(STATUS "————————————————————————————————————————————————————————————————————————————————————————")
message(STATUS "[NetCapture 库信息] ")

# LIST(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/out/install/lib/${NETCAPTURE_LIB_NAME}")
# foreach(module_name ${CMAKE_MODULE_PATH})
#     message("module_name: ${module_name}")
# endforeach()
set(NETCAPTURE_LIB_NAME "NetCapture")
set(Project_Include_Path "${CMAKE_BINARY_DIR}/include/${NETCAPTURE_LIB_NAME}")
set(Project_Library_Path "${CMAKE_BINARY_DIR}/lib")
message(STATUS "当前的头文件目录是: ${Project_Include_Path}")
message(STATUS "当前的库文件目录是: ${Project_Library_Path}")

# find_package(${NETCAPTURE_LIB_NAME} COMPONENTS Core::${NETCAPTURE_LIB_NAME} QUIET )
# message(STATUS "${NETCAPTURE_LIB_NAME}_FOUND: ${${NETCAPTURE_LIB_NAME}_FOUND}")

# 尝试查找库的头文件和库文件
find_path(${NETCAPTURE_LIB_NAME}_INCLUDE_DIR NAMES ${NETCAPTURE_LIB_NAME}.h 
        PATHS ${Project_Include_Path}
        NO_DEFAULT_PATH)

find_library(${NETCAPTURE_LIB_NAME}_LIBRARY NAMES ${NETCAPTURE_LIB_NAME} 
    PATHS ${Project_Library_Path}
        NO_DEFAULT_PATH)


# 设置 XXX_FOUND 变量
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(${NETCAPTURE_LIB_NAME} DEFAULT_MSG ${NETCAPTURE_LIB_NAME}_LIBRARY ${NETCAPTURE_LIB_NAME}_INCLUDE_DIR)

# 设置 ${NETCAPTURE_LIB_NAME}_INCLUDE_DIRS 和 ${NETCAPTURE_LIB_NAME}_LIBRARIES 变量
if(${NETCAPTURE_LIB_NAME}_FOUND AND NOT TARGET Core::${NETCAPTURE_LIB_NAME})
  add_library(Core::${NETCAPTURE_LIB_NAME} UNKNOWN IMPORTED)
  set_target_properties(Core::${NETCAPTURE_LIB_NAME} PROPERTIES
    IMPORTED_LOCATION "${${NETCAPTURE_LIB_NAME}_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${${NETCAPTURE_LIB_NAME}_INCLUDE_DIR}"
  )
endif()

mark_as_advanced(${NETCAPTURE_LIB_NAME}_INCLUDE_DIR ${NETCAPTURE_LIB_NAME}_LIBRARY)
message(STATUS "${NETCAPTURE_LIB_NAME}_FOUND: ${${NETCAPTURE_LIB_NAME}_FOUND}")
message(STATUS "${NETCAPTURE_LIB_NAME}_INCLUDE_DIR: ${${NETCAPTURE_LIB_NAME}_INCLUDE_DIR}")
message(STATUS "${NETCAPTURE_LIB_NAME}_LIBRARY: ${${NETCAPTURE_LIB_NAME}_LIBRARY}")


# find_library(${NETCAPTURE_LIB_NAME}_LIBRARY 
#     NAMES ${NETCAPTURE_LIB_NAME}
#     PATHS ${${NETCAPTURE_LIB_NAME}_Library_Path}
#     NO_DEFAULT_PATH
#     )
# find_path(${NETCAPTURE_LIB_NAME}_INCLUDE_PATH 
#     NAMES ${NETCAPTURE_LIB_NAME}.h
#     PATHS ${${NETCAPTURE_LIB_NAME}_Library_Path}
#     NO_DEFAULT_PATH
#     )
    
# message(STATUS "${NETCAPTURE_LIB_NAME}_Library_Path: ${${NETCAPTURE_LIB_NAME}_Library_Path}")
# message(STATUS "${NETCAPTURE_LIB_NAME}_LIBRARY: ${${NETCAPTURE_LIB_NAME}_LIBRARY}")

# if(${NETCAPTURE_LIB_NAME}_LIBRARY)
#     set(${NETCAPTURE_LIB_NAME}_LIBRARIES ${${NETCAPTURE_LIB_NAME}_LIBRARY})
#     message(STATUS "${NETCAPTURE_LIB_NAME}_LIBRARIES: ${${NETCAPTURE_LIB_NAME}_LIBRARIES}")   
#     set(${NETCAPTURE_LIB_NAME}_INCLUDE_PATH ${${NETCAPTURE_LIB_NAME}_LIBRARY})
#     message(STATUS "${NETCAPTURE_LIB_NAME}_INCLUDE_PATH: ${${NETCAPTURE_LIB_NAME}_INCLUDE_PATH}")
#     set(${NETCAPTURE_LIB_NAME}_LIBRARIES ${${NETCAPTURE_LIB_NAME}_LIBRARIES} ${${NETCAPTURE_LIB_NAME}_INCLUDE_PATH})
# else()
#     message(FATAL_ERROR "${NETCAPTURE_LIB_NAME} library not found")
# endif()